// Les fiches d'armes complètes de l'atelier (point de départ d'une conception) et les familles de munitions.
// Données seules : le concepteur, le catalogue et les tests les lisent sans dépendre de l'écran.
export const PRESETS={
  fusil:{name:'Fusil polyvalent',icon:'⌁',desc:'Précis, mobile, simple à ravitailler',p:{d:1.8,l:6.5,nose:'pointue',base:'bt',cons:'fmj',c:.032,L:150,twist:60,action:'semi',rof:450,mag:10,heavy:false,burn:1,wallx:1,jacket:1,core:0,hef:.3,fragm:4,zero:60,prop:'cartouche',fill:'tolite',shell:'lisse',fuse:'impact',mods:[]}},
  lancegrenades:{name:'Lance-grenades',icon:'◉',desc:'Explosif direct, léger, courte portée',p:{d:6,l:16.8,nose:'ronde',base:'plat',cons:'he',c:.054,L:75,twist:130,action:'pompe',rof:35,mag:4,heavy:false,burn:.7,wallx:1.1,jacket:1,core:0,hef:.38,fragm:4,zero:30,prop:'cartouche',fill:'tolite',shell:'rainuree',fuse:'impact',mods:['poignee']}},
  obusier:{name:'Obusier de campagne',icon:'◒',desc:'Tir en cloche, équipage et gros effet de zone',p:{d:20,l:65,nose:'ogive',base:'plat',cons:'he',c:3.5,L:420,twist:700,action:'culasse',rof:12,mag:1,heavy:true,burn:.65,wallx:1.8,jacket:1,core:0,hef:.48,fragm:18,zero:100,prop:'cartouche',fill:'tolite',shell:'rainuree',fuse:'impact',mods:['trepied','bouclier']}},
  fusee:{name:'Fusil-fusée à moustaches',icon:'➶',desc:'Balle-fusée guidée, deux étages, six ailettes',p:{d:3,l:12,nose:'ogive',base:'plat',cons:'he',c:.05,L:90,twist:200,action:'semi',rof:300,mag:4,heavy:false,burn:1,wallx:1,jacket:1,core:0,hef:.35,fragm:3,zero:60,prop:'fusee',fill:'tolite',shell:'rainuree',fuse:'impact',mods:['reflex'],fins:6,finSize:1.2,cant:6,stages:2,guide:'moustaches',ignite:40,stock:'squelette',finish:'kaki'}},
  mitrailleuse:{name:'Mitrailleuse à ailettes',icon:'≋',desc:'Bande de 150, radiateur de cuivre, trépied',p:{d:2.2,l:8,nose:'pointue',base:'bt',cons:'fmj',c:.05,L:260,twist:70,action:'auto',rof:650,mag:150,heavy:true,burn:1,wallx:1.6,jacket:1,core:0,hef:.3,fragm:4,zero:100,prop:'cartouche',fill:'tolite',shell:'lisse',fuse:'impact',mods:['trepied','ailettes','cacheflamme'],bands:1,neck:1.4,shoulder:35,finish:'bronze'}},
  carabine:{name:'Carabine de parade',icon:'✦',desc:'Bullpup gravée d’or, étui d’aluminium, méplat',p:{d:1.6,l:6,nose:'pointue',base:'bt',cons:'monolithique',c:.026,L:150,twist:55,action:'levier',rof:450,mag:8,heavy:false,burn:1,wallx:1,jacket:1,core:0,hef:.3,fragm:4,zero:60,prop:'cartouche',fill:'tolite',shell:'lisse',fuse:'impact',mods:['lunette','baionnette'],stock:'bullpup',finish:'grave',caseMat:'alu',meplat:.2,bands:2}},
  portatif:{name:'Obusier portatif',icon:'◔',desc:'10 mm, trois servants, transportable, portée et éclats réduits',p:{d:10,l:20,nose:'ogive',base:'plat',cons:'he',c:.22,L:170,twist:300,action:'culasse',rof:12,mag:1,heavy:false,burn:.65,wallx:1.1,jacket:1,core:0,hef:.45,fragm:8,zero:60,prop:'cartouche',fill:'tolite',shell:'rainuree',fuse:'impact',mods:['bipied'],carriage:'traineau'}},
  chasse:{name:'Fusil à pompe brutal',icon:'◆',desc:'Chevrotine, tube de 9 coups, pompe et canon court',p:{d:4.4,l:12,nose:'ronde',base:'plat',cons:'chevrotine',c:.075,L:105,twist:220,action:'pompe',rof:35,mag:9,heavy:false,burn:1.25,wallx:1.1,jacket:1,core:0,hef:.3,fragm:4,zero:22,prop:'cartouche',fill:'tolite',shell:'lisse',fuse:'impact',mods:['poignee'],feed:'tube',tube:'droit',stock:'bois'}},
  precision:{name:'Fusil extrême portée',icon:'⌖',desc:'Long tube lourd, lunette et munition très aérodynamique',p:{d:2.4,l:13,nose:'pointue',noseScale:1.8,base:'bt',boat:.65,cons:'monolithique',c:.11,L:480,twist:50,action:'verrou',rof:20,mag:6,heavy:true,burn:.65,wallx:2.1,jacket:1.5,core:.2,hef:.3,fragm:4,zero:240,prop:'cartouche',fill:'tolite',shell:'lisse',fuse:'impact',mods:['lunette','bipied','frein'],feed:'interne',tube:'lourd',stock:'bois',finish:'grave'}},
  microgatling:{name:'Micro-Gatling',icon:'✺',desc:'0,7 mm, huit tubes, 4 000 coups/min et bande',p:{d:.7,l:2.8,nose:'pointue',base:'bt',cons:'trc',c:.0024,L:145,twist:22,action:'rotatif',rof:4000,mag:800,heavy:true,burn:1.4,wallx:.8,jacket:.8,core:0,hef:.3,fragm:1,zero:80,prop:'cartouche',fill:'tolite',shell:'lisse',fuse:'impact',mods:['trepied','ailettes','reflex'],feed:'bande',tube:'refroidi',barrels:8,stock:'sans',finish:'bronze'}},
  forteresse:{name:'Obusier de siège',icon:'◉',desc:'40 mm, plateforme, cinq servants et obus énormes',p:{d:40,l:140,nose:'ogive',base:'plat',cons:'he',c:34,L:1200,twist:1500,action:'culasse',rof:6,mag:1,heavy:true,burn:.55,wallx:2.8,jacket:1,core:0,hef:.62,fragm:80,zero:500,prop:'cartouche',fill:'brisant',shell:'rainuree',fuse:'retard',mods:['bouclier','frein'],feed:'interne',tube:'lourd',carriage:'plateforme',stock:'sans',finish:'kaki'}},
  rupture:{name:'Pièce de rupture chimique',icon:'☄',desc:'100 mm fixe : ville lointaine, surpression, éclats et incendie chimique',p:{d:100,l:400,nose:'ogive',base:'plat',cons:'hei',c:350,L:3000,twist:3500,action:'culasse',rof:1,mag:1,heavy:true,burn:.55,wallx:2.7,jacket:1,core:0,hef:.85,fragm:220,zero:1200,prop:'cartouche',fill:'brisant',shell:'billes',fuse:'retard',mods:['bouclier','frein','trepied'],feed:'interne',tube:'lourd',carriage:'plateforme',stock:'sans',finish:'kaki'}},
  roquettes:{name:'Lance-roquettes multiple',icon:'➶',desc:'Six tubes, charge creuse autopropulsée et trépied',p:{d:18,l:62,nose:'ogive',base:'plat',cons:'creuse',c:4,L:240,twist:900,action:'rotatif',rof:90,mag:6,heavy:true,burn:1,wallx:.7,jacket:1,core:0,hef:.45,fragm:30,zero:160,prop:'fusee',fill:'brisant',shell:'rainuree',fuse:'impact',mods:['trepied','bouclier','reflex'],feed:'tremie',tube:'droit',barrels:6,fins:4,finSize:1.4,cant:5,stages:1,guide:'gyro',stock:'sans',finish:'kaki'}}};

export const FAMS=[['Ordinaires',['fmj','fmjm','plombnu','duplex','trc']],['Expansives',['sp','hp','monolithique','frangible','slug']],
  ['Perforantes',['ap','apt','tungstene','sabot','apfsds']],['Incendiaires, explosives',['inc','api','he','hei','saphei','creuse']],['Gerbes',['chevrotine','flechette']]];
export const CHOICE={caseMat:'laiton',rim:'sans',stock:'bois',finish:'bleui',guide:'aucun',feed:'boite',tube:'droit',carriage:'roues'};

// une fiche telle que l'atelier la charge : les choix de forme par défaut, puis la fiche
export const presetP=k=>{const P=PRESETS[k];if(!P)return null;return {noseScale:1,boat:P.p.base==='bt'?.3:0,rocketBurn:1,nozzle:1,...CHOICE,...JSON.parse(JSON.stringify(P.p))};};
