// Des parties entières, sans personne : un joueur simple bâtit, se nourrit, forme une armée à la caserne et défend ;
// les Bèè vivent leur vie (paix armée, expansion, guerre, raids, défense). On cherche ce qui casse ou se bloque.
//   node test/campagne.mjs [parties] [jours] [graine]
const out={textContent:''};globalThis.document??={getElementById:()=>out};
const {World}=await import('../js/world.js');
const {BUILDINGS,DAY}=await import('../js/data.js');
const GAMES=+(process.argv[2]||3),DAYS=+(process.argv[3]||42),SEED=+(process.argv[4]||101);
const d2=(a,b,c,d)=>Math.hypot(a-c,b-d);
// le joueur automatique commun (bot.mjs) : celui de ce fichier plaçait encore des champs et des fermes, disparus en V6
const {player}=await import('./bot.mjs');
for(let g=0;g<GAMES;g++){const seed=SEED+g;const W=new World(seed);const P=player(W);const ev={};const errs=[];let worst=0,slowH=0;const t0=Date.now();const daily=[];
  for(let h=0;h<DAYS*24;h++){try{P.tick();}catch(e){errs.push('joueur j'+W.day+': '+e.message);}
    const a=performance.now();try{W.update(1);}catch(e){errs.push('monde j'+W.day+': '+e.message+' '+(e.stack||'').split('\n')[1]);if(errs.length>5)break;}const dt=performance.now()-a;if(dt>worst){worst=dt;slowH=W.day;}
    for(const e of W.events.splice(0)){ev[e.type]=(ev[e.type]||0)+1;if(e.type==='band')ev['groupe:'+e.state]=(ev['groupe:'+e.state]||0)+1;if((e.type==='down'||e.type==='death')&&e.f==='meumeu'){const c=e.cause||W.unit(e.id)?.h?.cause||(e.type==='death'?'mort':'?');ev.causes??={};ev.causes[c]=(ev.causes[c]||0)+1;}}
    if(h%24===23){const B=W.s.beee;daily.push({j:W.day,pop:W.s.units.filter(u=>u.f==='meumeu').length,sold:W.s.units.filter(u=>u.f==='meumeu'&&u.w).length,bee:W.s.units.filter(u=>u.f==='beee'&&u.hp>0).length,villes:B.cities.filter(c=>!c.fallen).length,groupes:(B.bands||[]).map(b=>{const m=W.bandMembers(b).filter(u=>u.hp>0);const c=m.length?[m.reduce((a,u)=>a+u.x,0)/m.length,m.reduce((a,u)=>a+u.y,0)/m.length]:[0,0];const t=W.building(b.target);return (b.kind||'raid')+':'+b.state+'('+m.length+(process.env.DBG?' à '+Math.round(c[0])+','+Math.round(c[1])+(t?' cible '+t.k+' '+t.i+','+t.j:''):'')+')';}).join(' '),viv:Math.round(W.capital()?.stock.vivres||0),dbg:process.env.DBG?`bât ${W.s.buildings.filter(b=>b.f==='meumeu').map(b=>b.k+(b.done?'':'…')).join(',')} · fait ${Object.keys(P.did).join(',')} · caserne ${(W.s.buildings.find(b=>b.f==='meumeu'&&b.k==='caserne')?.inside||[]).length} dedans · fusils ${W.have('meumeu',W.capital().i+1,W.capital().j+1)['a:mle1']||0}`:''});}}
  const B=W.s.beee;const lostB=W.s.buildings.filter(b=>b.f==='meumeu'&&b.ruin).length;
  console.log(`\n=== partie ${g+1} (graine ${seed}) · ${DAYS} jours en ${((Date.now()-t0)/1000).toFixed(0)} s · pire heure ${Math.round(worst)} ms (jour ${slowH}) · guerre au jour ${B.warDay}`);
  console.log(`  erreurs : ${errs.length?errs.join(' | '):'aucune'}`);
  console.log(`  Meumeu : ${W.s.units.filter(u=>u.f==='meumeu').length} vivants, ${W.s.units.filter(u=>u.f==='meumeu'&&u.w).length} armés, morts ${W.s.corpses.filter(c=>c.f==='meumeu').length} · bâtiments en ruine ${lostB} · capitale ${W.capital()?.ruin?'TOMBÉE':Math.round(W.capital().hp)+'/'+W.capital().max}`);
  console.log(`  Bèè : ${W.s.units.filter(u=>u.f==='beee'&&u.hp>0).length} vivants, morts ${W.s.corpses.filter(c=>c.f==='beee').length}, villes ${B.cities.filter(c=>!c.fallen).length}/${B.cities.length}, raids ${ev.wave||0}, défenses ${ev['groupe:defense']||0}, replis ${ev.rout||0}, voies coupées ${ev['rail-cut']||0}, dépôts sautés ${W.s.log.filter(l=>/a sauté/.test(l.text)).length}`);
  console.log(`  prêts : bèè ${W.beeeReady()} (${['ferme','atelier','poudrerie','caserne','arsenal'].filter(k=>!W.s.buildings.some(b=>b.f==='beee'&&b.k===k&&b.done)).join(',')||'tout'} manque), meumeu ${W.meumeuReady()} · soldats bèè ${W.s.units.filter(u=>u.f==='beee'&&u.k==='soldat').length} · usines bèè ${W.s.buildings.filter(b=>b.f==='beee'&&(b.k==='manufacture'||b.k==='arsenal')).map(b=>b.k+':'+b.prod+(b.done?'':'(chantier)')).join(',')} · maisons ${W.s.buildings.filter(b=>b.f==='beee'&&b.k==='maison').length}`);console.log(`  renseignement bèè : ${Object.keys(W.s.beee.known||{}).length} bâtiments connus sur ${W.s.buildings.filter(b=>b.f==='meumeu').length} · piste ${W.s.beee.lead?Math.round(W.s.t-W.s.beee.lead.t)+' h ('+(W.s.beee.lead.why||'vu')+')':'aucune'} · reconnaissances ${W.s.beee.cities.map(c=>c.scoutN||0).join(',')}`);console.log(`  causes (Meumeu) : ${JSON.stringify(ev.causes||{})}`);
  console.log(`  tirs ${ev.shot||0} · blessures ${ev.wound||0} · à terre ${ev.down||0} · morts ${ev.death||0}`);
  for(const d of daily.filter((d,i)=>i%4===3||d.groupes))console.log((d.dbg?'   '+d.dbg+String.fromCharCode(10):'')+`   j${d.j} : Meumeu ${d.pop} (${d.sold} armés), vivres ${d.viv} · Bèè ${d.bee} en ${d.villes} villes · ${d.groupes||'—'}`);}
