import assert from 'node:assert/strict';
import {World} from '../js/world.js';
import {FixedClock,advanceSolar,solarRemaining} from '../js/clock.js';
import {derive,pToKit,kitToP,editKit,TILE_M} from '../js/ballistics.js';
import {DEFAULT_DESIGNS} from '../js/designs.js';
import {View} from '../js/view.js';
let passed=0;const check=(name,fn)=>{fn();passed++;console.log('PASS',name);};const close=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
check('Nuit complète = 360 secondes à 1×',()=>{close(advanceSolar(17,360),8);close(solarRemaining(17).seconds,360);});
check('Jour complet = 240 secondes',()=>close(advanceSolar(8,240),17));
check('Cycle solaire traverse minuit sans perte',()=>close(advanceSolar(17,600),17));
for(const speed of [.5,1,2,4])check('Horloge multiplicateur '+speed,()=>{let t=0;const c=new FixedClock();for(let i=0;i<100;i++)c.advance(.033,speed,s=>t+=s);close(t+c.debt,3.3*speed);});
check('Dette conservée sous surcharge et drainée',()=>{let t=0,c=new FixedClock();c.advance(3,4,s=>t+=s);assert.ok(c.debt>0);while(c.debt>=.05-1e-8)c.advance(0,4,s=>t+=s);close(t,12);});
check('Pause ne fait pas avancer la simulation',()=>{let c=new FixedClock();c.advance(4,0,()=>assert.fail());assert.equal(c.elapsed,0);});
const p=structuredClone(DEFAULT_DESIGNS.find(d=>d.id==='mle1').p),D=derive(p);
check('Aller-retour du concepteur sans modification exact',()=>assert.deepEqual(kitToP(pToKit(p)),p));
check('Changer le zéro ne change pas V₀',()=>close(derive({...p,zero:200}).v0,D.v0));
check('Grossissement ne change pas V₀',()=>close(derive({...p,mods:[...(p.mods||[]),'lunette'],sightMag:4}).v0,D.v0));
check('Tube court : baisse V₀ sans effondrement de masse',()=>{const short=derive({...p,L:110}),long=derive({...p,L:240});assert.ok(long.v0>short.v0+30);assert.ok(long.massEmpty-short.massEmpty<.2);});
check('Édition classique garde le kit et modifie le tube',()=>{const q=structuredClone(DEFAULT_DESIGNS.find(d=>d.id==='canon_mle1').p);q.L=300;editKit(q,'L');assert.equal(q.kit.barrelLengthCm,30);});
const w=new World(301),original=w.serialize();
check('Économie et calendrier solaire indépendants',()=>{const h=w.hour();w.s.t+=100;assert.equal(w.hour(),h);});
check('Sauvegarde restaure calendrier, équipes et RNG',()=>{const a=new World(1).restore(original),b=new World(2).restore(original);assert.equal(a.hour(),7);assert.deepEqual(a.s.units,b.s.units);assert.equal(a.rand(),b.rand());});
check('Sauvegarde préserve Infinity des ordres',()=>{w.s.units[0].task={kind:'zone',n:Infinity};const a=new World(1).restore(w.serialize());assert.equal(a.s.units[0].task.n,Infinity);});
check('Save étrangère rejetée sans effacer',()=>assert.throws(()=>w.restore('{"format":"AUTRE"}')));
const soldier=w.addUnit('meumeu','soldat',150,150,{w:'mle1'});w.gridBuild();soldier.fx=1;soldier.fy=0;w.s.solar=12;
check('Champ de vision orienté',()=>assert.ok(w.visualRange(soldier,160,150)>w.visualRange(soldier,140,150)));
check('Vision nocturne change réellement la portée',()=>{w.s.solar=22;soldier.bino=35;soldier.irLeft=8;soldier.nvOn=false;const r=w.visualRange(soldier,170,150);soldier.nvOn=true;assert.ok(w.visualRange(soldier,170,150)>r);});
check('Acoustique plus précise quand on se rapproche',()=>{const a=w.acousticContact(soldier,154,150,190,'train'),b=w.acousticContact(soldier,174,150,190,'train');assert.ok(a.uncertainty<b.uncertainty);assert.equal(a.x,undefined);assert.equal(a.y,undefined);});
check('FX cachés refusés même sans faction renseignée',()=>{const v={world:w,fogVis:new Uint8Array(w.N*w.N)};assert.equal(View.prototype.fxVisible.call(v,300,300),false);assert.equal(View.prototype.fxVisible.call(v,300,300,'beee'),false);});
const op=w.prepareOperation([soldier.id]).op;
check('Programme sans étapes ne part pas',()=>assert.equal(w.startOperation(op.id).ok,false));
check('Approche + observation + retour acceptés',()=>{w.addOperationStep(op.id,{kind:'approche',point:[152,150]});w.addOperationStep(op.id,{kind:'observation',point:[160,150],seconds:1});w.addOperationStep(op.id,{kind:'retour'});assert.equal(w.startOperation(op.id).ok,true);});
check('Ordre manuel suspend immédiatement le programme',()=>{w.order([soldier.id],{type:'point',x:155,y:150});assert.equal(op.state,'suspendue');assert.equal(soldier.op,null);});
check('Compteur de bilan ne compte pas les munitions perdues comme tirées',()=>{op.initial={[soldier.id]:{ammo:99,charges:2}};op.fired=3;op.planted=1;soldier.mag=0;soldier.pouch=0;const r=w.operationResult(op);assert.equal(r.ammo,3);assert.equal(r.charges,1);});
check('Retour clôturé seulement au point réel',()=>{soldier.x=170;w.returnOperation(op.id);w.operationTick();assert.equal(op.state,'retour');soldier.x=op.home[0];soldier.y=op.home[1];w.operationTick();assert.equal(op.state,'terminee');});
check('Sabotage ne détruit plus un gisement entier',()=>{const n=w.s.nodes.find(n=>n.type==='ore');const left=n.left;w.s.charges=[{node:n.id,t:0,x:n.i+.5,y:n.j+.5,f:'meumeu'}];w.chargesTick();assert.equal(n.left,left);assert.ok(n.sabUntil>w.t);});
check('Artillerie lit sa propre conception et les servants',()=>{const gun=w.addUnit('meumeu','canon',160,160);assert.equal(gun.w,'canon_mle1');assert.ok(w.W(gun.w).crew>=2);assert.equal(w.servants(gun).length,0);assert.ok(w.zoneRange(w.W(gun.w))>14);});
check('Pièce sous-servie peut encore charger avec un lourd malus',()=>{const q=new World(88);q.declareWar('meumeu');const gun=q.addUnit('meumeu','soldat',200,200,{w:'canon_mle1'}),Wd=q.W(gun.w),A=q.arcOf(Wd),R=Math.max(A.min*1.2,Math.min(A.max*.5,(A.min+A.max)/2));gun.mag=0;gun.pouch=3;gun.reload=0;gun.cool=0;gun.deployT=1e6;gun.moved=-99;q.dt=q.dts=.01;
  const T={x:gun.x+R/TILE_M,y:gun.y,high:true,bias:null,fired:0};assert.equal(q.servants(gun).length,0);assert.equal(q.zoneTick(gun,T),true);assert.ok(gun.reload>0||gun.mag>0);assert.doesNotMatch(gun.why||'',/équipage incomplet/);});
check('IA ne connaît pas un bâtiment hors vue',()=>{w.s.beee.known={};w.s.beee.reports=[];w.dt=1;w.beeeScout();assert.equal(w.s.beee.known[w.capital().id],undefined);});
check('Rapport de reconnaissance transmis avec délai',()=>{const old=w.visibleAt;w.visibleAt=f=>f==='beee';w.beeeScout();assert.equal(w.s.beee.known[w.capital().id],undefined);w.s.t+=3;w.beeeScout();assert.equal(typeof w.s.beee.known[w.capital().id],'object');w.visibleAt=old;});
check('Évaluation des cibles refuse un renseignement périmé',()=>{w.s.beee.known={[w.capital().id]:{id:w.capital().id,done:true,x:60,y:380,k:'centre',capital:true,t:w.t-200,troops:0,defense:0}};assert.equal(w.beeePlanRaid({x:380,y:60},Array(30).fill({})),null);});
check('Évaluation choisit une cible connue accessible en effectifs',()=>{const b=w.capital();w.s.beee.known={[b.id]:{id:b.id,done:true,x:60,y:380,k:'centre',capital:true,t:w.t,troops:2,defense:0}};const plan=w.beeePlanRaid({x:380,y:60},Array(30).fill({}));assert.equal(plan.target.id,b.id);assert.ok(plan.need>=4);});
check('Itinéraire de patrouille part hors du centre occupé',()=>{const c=w.s.beee.cities[0];assert.ok(w.reachablePatrol(c,w.freeSpot(c.x-30,c.y+20,8)).length>0);});
check('Deux villes, au moins 56 civils et 24 soldats ennemis au départ',()=>{const q=new World(77);assert.equal(q.s.beee.cities.length,2);assert.ok(q.s.units.filter(u=>u.f==='beee'&&u.k==='villageois').length>=56);assert.ok(q.s.units.filter(u=>u.f==='beee'&&u.w).length>=24);});
check('Explosion détruit une tuile ferroviaire et laisse un cratère franchissable',()=>{const q=new World(77),k=150*q.N+150;q.s.rails[k]={f:'beee',b:1,p:1,hp:100};q.rail[k]=2;q.blast(150.5,150.5,'bombe','meumeu',null);assert.ok(!q.s.rails[k]||!q.s.rails[k].b);assert.ok(q.s.craters.length>0);assert.ok(q.crater[k]>0);assert.ok(Number.isFinite(q.costFn('meumeu')(k)));});
check('Accès au minerai saboté bloque vraiment la récolte',()=>{const q=new World(77),n=q.s.nodes.find(n=>n.type==='ore'),u=q.s.units[0],left=n.left;n.sabUntil=q.t+24;q.gatherTick(u,{kind:'gather',node:n.id,res:n.res,type:'ore'},1);assert.equal(n.left,left);assert.match(u.why,/saboté/);});
check('Programme approche-observation-retour exécuté sans téléportation',()=>{const q=new World(77);q.beeeTick=()=>{};const c=q.capital(),p=q.freeSpot(c.i+9,c.j+6,8),goal=q.freeSpot(p[0]+6,p[1]+3,8);const u=q.addUnit('meumeu','soldat',...p,{w:'mle1'});u.mag=5;u.pouch=100;const o=q.prepareOperation([u.id]).op;q.addOperationStep(o.id,{kind:'approche',point:goal});q.addOperationStep(o.id,{kind:'observation',point:[goal[0]+8,goal[1]],seconds:1});q.addOperationStep(o.id,{kind:'retour'});assert.ok(q.startOperation(o.id).ok);let walked=0,px=u.x,py=u.y;for(let n=0;n<2400&&o.state!=='terminee';n++){q.update(.05);walked+=Math.hypot(u.x-px,u.y-py);px=u.x;py=u.y;q.events=[];}assert.equal(o.state,'terminee',o.why||u.why);assert.ok(walked>3);assert.equal(o.result.returned,1);assert.equal(o.result.ammo,0);});
console.log(JSON.stringify({passed,failed:0}));
